branch-defaults:
  main:
    environment: aeroreserve-ticket-booking-service-prod
    group_suffix: null
environment-defaults:
  aeroreserve-ticket-booking-service-prod:
    branch: main
    repository: aeroreserve-ticket-booking-service
global:
  application_name: aeroreserve-ticket-booking-service
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Corretto 17 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: aeroreserve-ticket-booking-service
  sc: git
  workspace_type: Application
